/**
 * Sovereign — Narrative Memory Types
 *
 * The memory system is the narrative brain. Every card reads from it.
 * Every swipe writes to it. It persists across the entire 48-week term.
 *
 * Memory stores flags (boolean markers), choices (decision history),
 * witnessed events (dramatic irony), and played cards (duplicate prevention).
 *
 * @see SOV_PRD_07_NARRATIVE_ENGINE — memory object, flags, text resolver, card selector
 */

import type { Direction } from './game';

// ---------------------------------------------------------------------------
// Memory Object
// ---------------------------------------------------------------------------

/**
 * The core memory object that persists across the entire 48-week term.
 * Every card reads from memory (conditions, text functions) and every
 * swipe writes to it (flags, choices, witnessed).
 */
export interface Memory {
  /**
   * Boolean markers set by card outcomes.
   * Cards set flags; other cards' conditions read them.
   *
   * Examples: "raised_taxes", "discovered_mining_scandal", "conv_elara_done"
   */
  flags: Set<string>;

  /**
   * Every decision recorded with context.
   * Used by text functions to reference past choices and for analytics.
   */
  choices: Choice[];

  /**
   * Dramatic irony markers. The PLAYER knows this information but
   * their CHARACTER does not. Set by interlude cards.
   *
   * Examples: "witnessed_kira" (saw Kira plotting), "witnessed_elara" (saw Elara's letter)
   */
  witnessed: Set<string>;

  /**
   * Set of card IDs that have been played this term.
   * Used by the card selector to prevent duplicates and track
   * once-only cards.
   */
  cardsPlayed: Set<string>;
}

// ---------------------------------------------------------------------------
// Choice Record
// ---------------------------------------------------------------------------

/**
 * A single recorded decision from the player's history.
 * Appended to memory.choices after every card resolves.
 */
export interface Choice {
  /** Which card was played. */
  cardId: string;

  /** Direction the player swiped. */
  direction: Direction;

  /** The label text of the chosen option. */
  label: string;

  /** Week number when the choice was made (1-48). */
  week: number;

  /** Optional outcome description for analytics/recap. */
  outcome?: string;
}

// ---------------------------------------------------------------------------
// Memory Operations (function signatures)
// ---------------------------------------------------------------------------

/**
 * Creates a fresh memory object for a new game term.
 */
export type CreateMemoryFn = () => Memory;

/**
 * Checks whether a flag exists in memory.
 */
export type HasFlagFn = (memory: Memory, flag: string) => boolean;

/**
 * Adds one or more flags to memory.
 */
export type AddFlagsFn = (memory: Memory, flags: string[]) => void;

/**
 * Records a player choice in memory.
 */
export type AddChoiceFn = (
  memory: Memory,
  cardId: string,
  direction: Direction,
  label: string,
  week: number,
) => void;

/**
 * Marks a card as played in memory.
 */
export type MarkPlayedFn = (memory: Memory, cardId: string) => void;

/**
 * Adds a witnessed event to memory (dramatic irony).
 */
export type AddWitnessedFn = (memory: Memory, eventId: string) => void;

// ---------------------------------------------------------------------------
// Card Selector Priority
// ---------------------------------------------------------------------------

/**
 * Priority levels used by the card selector to determine which card
 * appears next. Lower number = higher priority.
 *
 * 1. Follow-up cards (consequences of past choices)
 * 2. Conversations (every 6th card, deepen NPC relationships)
 * 3. Interludes (every 8th card, dramatic irony)
 * 4. District cards (crisis generated by territory state)
 * 5. Base cards (standard governance decisions)
 */
export type CardPriority = 1 | 2 | 3 | 4 | 5;

/**
 * The reason a card was selected, useful for debugging and analytics.
 */
export type SelectionReason =
  | 'follow_up'
  | 'conversation'
  | 'interlude'
  | 'district_crisis'
  | 'base_card';

/** Interval at which conversation cards are injected. */
export const CONVERSATION_INTERVAL = 6;

/** Interval at which interlude cards are injected. */
export const INTERLUDE_INTERVAL = 8;
